<?xml version="1.0" encoding="utf-8"?><Database Name="AssetDB" Class="LinqToAssetDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\Projects;Initial Catalog=AssetDB;Integrated Security=True;Connect Timeout=30" SettingsObjectName="MapEditor.Properties.Settings" SettingsPropertyName="AssetDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Asset" Member="Assets">
    <Type Name="Asset">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Parent" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>